part of animal;

List<Animal> animal_list = [new Animal("Liobogrus reini", "ギギ科", "アカザ属", "akaza", "アカザ",
            4, true, false, false, false, true, false, false, false),
new Animal("Chiromantes haematochir", "ベンケイガニ科", "", "akategani", "アカテガニ",
            2, false, false, true, true, false, false, true, true),
new Animal("Cynops pyrrhogaster", "イモリ科", "トウヨウイモリ属", "akaharaimori", "アカハライモリ",
            2, true, true, false, false, true, true, false, false),
new Animal("Tanakia limbata", "コイ科タナゴ亜科", "アブラボテ属", "aburabote", "アブラボテ",
            3, false, true, false, false, false, true, false, false),
new Animal("Mugilogobius abei", "ハゼ科ハゼ亜科", "アベハゼ属", "abehaze", "アベハゼ",
            4, false, true, true, false, false, true, true, false),
new Animal("Salmo (Oncorhynchus) masou macrostimus", "サケ科", "サケ属", "amago", "アマゴ",
            2, true, false, false, false, true, false, false, false),
new Animal("Procambarus clarkii", "アメリカザリガニ科", "アメリカザリガニ属", "amerikazarigani", "アメリカザリガニ",
            3, false, true, true, false, false, true, true, false),
new Animal("Plecoglossus altivelis altivelis", "キュウリウオ科", "アユ属", "ayu", "アユ",
            2, false, true, true, true, false, true, true, true),
new Animal("Cottus kazika", "カジカ科", "カジカ属", "ayukake", "アユカケ",
            3, false, true, true, true, false, true, true, true),
new Animal("Cobitis takatsuensis", "ドジョウ科", "シマドジョウ属", "ishidojou", "イシドジョウ",
            5, true, false, false, false, true, false, false, false),
new Animal("Odontobutis hikimiusu", "ハゼ科カワアナゴ亜科", "ドンコ属", "ishidonko", "イシドンコ",
            5, true, false, false, false, false, false, false, false),
new Animal("Clithon retropicta", "アマオブネガイ科", "", "ishimakigai", "イシマキガイ",
            1, false, false, true, true, false, false, true, true),
new Animal("Squalidus gracilis gracilis", "コイ科カマツカ亜科", "スズモロコ属", "itomoroko", "イトモロコ",
            3, false, true, false, false, false, true, false, false),
new Animal("Chaenogobius urotaenia", "ハゼ科ハゼ亜科", "ウキゴリ属", "ukigori", "ウキゴリ",
            3, false, false, true, true, false, false, true, true),
new Animal("Leuciscus", "コイ科ウグイ亜科", "ウグイ属", "ugui", "ウグイ",
            1, true, true, true, true, true, true, true, true),
new Animal("Cottus reinii", "カジカ科", "カジカ属", "utsusemikajika", "ウツセミカジカ",
            3, false, true, true, true, false, true, true, true),
new Animal("Anguilla japonica", "ウナギ科", "ウナギ属", "unagi", "ウナギ",
            3, true, true, true, true, true, true, true, true),
new Animal("Glossogobius olivaceus", "ハゼ科ハゼ亜科", "ウロハゼ属", "urohaze", "ウロハゼ",
            3, false, false, true, true, false, false, true, true),
new Animal("Zacco platypus", "コイ科ハエジャコ亜科", "オイカワ族", "oikawa", "オイカワ",
            3, false, true, false, false, false, true, false, false),
new Animal("Rhinogobius sp.LD", "ハゼ科ハゼ亜科", "ヨシノボリ属", "ooyoshinobori", "オオヨシノボリ",
            4, true, true, false, false, false, false, false, false),
new Animal("Siniperca (Bryttosus) kawamebari", "スズキ科", "ケツギョ属", "oyanirami", "オヤニラミ",
            4, true, false, false, false, false, false, false, false),
new Animal("Cottus pollux", "カジカ科", "カジカ属", "kajika", "カジカ",
            5, false, true, false, false, false, true, false, false),
new Animal("Buergeria buergeri", "アオガエル科", "カジカガエル属", "kajikagaeru", "カジカガエル",
            4, true, false, false, false, true, false, false, false),
new Animal("Pseudogobio esocinus esocinus", "コイ科カマツカ亜科", "カマツカ属", "kamatsuka", "カマツカ",
            2, true, true, false, false, true, true, false, false),
new Animal("Eleotris oxycephala", "ハゼ科カワアナゴ亜科", "カワアナゴ属", "kawaanago", "カワアナゴ",
            5, false, false, false, true, false, false, false, true),
new Animal("Semisulcospira libertina", "カワニナ科", "", "kawanina", "カワニナ",
            1, true, true, true, false, true, true, true, false),
new Animal("Zacco temmincki", "コイ科ハエジャコ亜科", "オイカワ属", "kawamutsu", "カワムツ",
            1, true, true, true, false, true, true, true, false),
new Animal("Rhinogobius flumineus", "ハゼ科ハゼ亜科", "ヨシノボリ族", "kawayoshinobori", "カワヨシノボリ",
            2, true, true, false, false, true, true, false, false),
new Animal("Pseudobagrus nudiceps", "ギギ科", "ギギ属", "gigi", "ギギ",
            2, true, true, false, false, true, true, false, false),
new Animal("Carassius gibelio langsdorfi", "コイ科コイ亜科", "フナ属", "ginbuna", "ギンブナ",
            1, false, true, true, false, false, true, true, false),
new Animal("Chinemys reevesii", "イシガメ科", "イシガメ属", "kusagame", "クサガメ",
            4, false, true, true, false, false, true, true, false),
new Animal("Acanthopagrus schlegeli", "タイ科", "クロダイ属", "kurodai", "クロダイ",
            2, false, false, false, true, false, false, false, true),
new Animal("Chiromantes dehaani", "ベンケイガニ科", "アカテガニ属", "kurobenkeigani", "クロベンケイガニ",
            2, false, false, true, true, false, false, true, true),
new Animal("Hemigrapsus intermedium", "モクズカニ科", "イソガニ属", "kehusaisogani", "ケフサイソガニ",
            3, false, false, false, true, false, false, false, false),
new Animal("Cyprinus carpio", "コイ科コイ亜科", "コイ属", "koi", "コイ",
            2, false, true, true, false, false, true, true, false),
new Animal("Platycephalus indicus", "コチ科", "コチ属", "koti", "コチ",
            2, false, false, false, true, false, false, false, true),
new Animal("Salvelinus leucomaenis f.imbrius", "サケ科サケ亜科", "イワナ属", "gogi", "ゴギ",
            4, true, false, false, false, false, false, false, false),
new Animal("Rhinogobius giurinus", "ハゼ科ハゼ亜科", "ヨシノボリ属", "gokurakuhaze", "ゴクラクハゼ",
            2, false, true, true, true, false, true, true, true),
new Animal("Salmo (Oncorhynchus) masou masou", "サケ科サケ亜科", "サケ属", "sakuramasu", "サクラマス",
            5, false, true, true, true, false, false, false, false),
new Animal("Hyporhamplus sajori", "サヨリ科", "サヨリ属", "sayori", "サヨリ",
            3, false, false, false, true, false, false, false, true),
new Animal("Geothelphusa dehaani", "サワガニ科", "サワガニ属", "sawagani", "サワガニ",
            3, true, false, false, false, true, false, false, false),
new Animal("Terapon (Rhyncopelates) oxyrhynchus", "シマイサキ科", "コトヒキ属", "shimaisaki", "シマイサキ",
            3, false, false, true, true, false, false, true, true),
new Animal("Cobitis biwae", "ドジョウ科", "シマドジョウ属", "shimadojou", "シマドジョウ",
            3, true, true, false, false, true, true, false, false),
new Animal("Rhinogobius sp.CB", "ハゼ科", "ヨシノボリ属", "shimayoshinobori", "シマヨシノボリ",
            3, false, true, false, false, false, true, false, false),
new Animal("Leucopsarion petersi", "ハゼ科ハゼ亜科", "シロウオ属", "shirouo", "シロウオ",
            5, false, false, false, false, false, false, false, true),
new Animal("Sillago japonica (Temminck et Schlegel)", "キス科", "キス属", "shirogisu", "シロギス",
            3, false, false, true, true, false, false, true, true),
new Animal("Lateolabrax japonicus", "スズキ科", "スズキ属", "suzuki", "スズキ",
            2, false, false, true, true, false, true, true, true),
new Animal("Lampetra (Lethenteron) reissneri", "ヤツメウナギ科", "ヤツメウナギ属", "sunayatsume", "スナヤツメ",
            5, true, false, false, false, false, false, false, false),
new Animal("Chaenogobius sp.2", "ハゼ科ハゼ亜科", "ウキゴリ属", "sumiukigori", "スミウキゴリ",
            3, false, true, true, false, false, true, true, true),
new Animal("Rhodeus ocellatus ocellatus", "コイ科タナゴ亜科", "バラタナゴ属", "tairikubaratanago", "タイリクバラタナゴ",
            4, false, false, true, false, false, false, false, false),
new Animal("Phoxinus oxycephalus jouyi", "コイ科", "コイ属", "takahaya", "タカハヤ",
            2, true, false, false, false, true, false, false, false),
new Animal("Tridentiner obscurus", "ハゼ科ハゼ亜科", "チチブ属", "titibu", "チチブ",
            2, false, false, true, true, false, false, true, true),
new Animal("Rana rugosa", "アカガエル科", "アカガエル属", "tsutigaeru", "ツチガエル",
            1, false, true, true, false, false, true, true, false),
new Animal("Macrobrachium nipponense", "テナガエビ科", "", "tenagaebi", "テナガエビ",
            2, false, true, true, true, false, true, true, true),
new Animal("Rhinogobius sp.OR", "ハゼ科ハゼ亜科", "ヨシノボリ属", "touyoshinobori", "トウヨシノボリ",
            4, false, true, false, false, false, false, false, false),
new Animal("Rana nigromaculata", "アカガエル科", "トノサマカエル属", "tonosamagaeru", "トノサマガエル",
            2, true, true, true, false, true, true, true, false),
new Animal("Misgurnus anguillicaudatus", "ドジョウ科", "ドジョウ属", "dojou", "ドジョウ",
            2, false, true, true, false, false, true, true, false),
new Animal("Odontobutis obscura obscura", "ハゼ科カワアナゴ亜科", "ドンコ属", "donko", "ドンコ",
            1, false, true, true, false, false, true, true, false),
new Animal("Silurus asotus", "ナマズ科", "ナマズ属", "namazu", "ナマズ",
            3, false, true, true, false, false, true, true, false),
new Animal("Mauremys japanica", "イシガメ科", "イシガメ属", "nihonnishigame", "ニホンイシガメ",
            4, true, true, true, false, true, true, true, false),
new Animal("Pelodiscus sinensis", "スッポン科", "キョクトウスッポン属", "nihonsuppon", "ニホンスッポン",
            4, false, true, true, false, false, true, true, false),
new Animal("Fejervarya limnocharis", "ヌマガエル科", "ヌマガエル属", "numagaeru", "ヌマガエル",
            2, true, true, false, false, true, true, false, false),
new Animal("Tridentiger kuroiwae brevispinis", "ハゼ科ハゼ亜科", "チチブ属", "numatitibu", "ヌマチチブ",
            3, false, true, true, false, false, true, true, false),
new Animal("Redigobius bikolanus", "ハゼ科ハゼ亜科", "ヒナハゼ属", "hinahaze", "ヒナハゼ",
            3, false, false, true, true, false, false, true, true),
new Animal("Favonigobius gymnauchen", "ハゼ科ハゼ亜科", "ヒメハゼ属", "himehaze", "ヒメハゼ",
            2, false, false, false, true, false, false, false, true),
new Animal("Lateolabrax latusb Katayama", "スズキ科", "スズキ属", "hirasuzuki", "ヒラスズキ",
            3, false, false, false, true, false, false, false, false),
new Animal("Paralichthys olivaceus (Temmink et Schlegel)", "ヒラメ科", "ヒラメ属", "hirame", "ヒラメ",
            3, false, false, false, true, false, false, false, false),
new Animal("Chaenogobius castaneus", "ハゼ科ハゼ亜科", "ウキゴリ属", "biringo", "ビリンゴ",
            4, false, false, true, true, false, false, true, true),
new Animal("Sesarmops intermedium", "ベンケイガニ科", "", "benkeigani", "ベンケイガニ",
            3, false, false, true, true, false, false, true, true),
new Animal("Mugil cephalus cephalus", "ボラ科", "ボラ属", "bora", "ボラ",
            1, false, true, true, true, false, true, true, true),
new Animal("Pronodularia jananensis", "イシガイ科", "", "matsukasagai", "マツカサガイ",
            5, false, true, false, false, false, false, false, false),
new Animal("Acanthogobius flavimanus", "ハゼ科ハゼ亜科", "マハゼ属", "mahaze", "マハゼ",
            2, false, false, true, true, false, true, true, true),
new Animal("Cipangopaludina japonica", "タニシ科", "タニシ属", "marutanishi", "マルタニシ",
            2, false, true, true, false, false, true, true, false),
new Animal("Trachemys scripta elegans", "ヌマガメ科", "アカミミガメ属", "mishishippiakamimigame", "ミシシッピアカミミガメ",
            2, false, false, true, false, false, false, true, false),
new Animal("Luciogobius guttatus", "ハゼ科ハゼ亜科", "ミミズハゼ属", "mimizuhaze", "ミミズハゼ",
            4, false, false, false, true, false, false, false, false),
new Animal("Pungtungia herzi", "コイ科ヒガイ亜科", "ムギツク属", "mugitsuku", "ムギツク",
            3, false, true, false, false, false, false, false, false),
new Animal("Oryzias latipes", "メダカ科", "メダカ属", "medaka", "メダカ",
            3, false, true, true, true, false, true, true, true),
new Animal("Physa acuta", "モノアラガイ科", "モノアラガイ属", "monoaragai", "モノアラガイ",
            3, false, true, true, false, false, true, true, false),
new Animal("Salmi (Oncorhynchus) masou masou", "サケ科サケ亜科", "サケ属", "yamame", "ヤマメ",
            3, true, false, false, false, true, false, false, false),
];

Map<String, Animal> animal_map = new Map.fromIterable(animal_list,
    key: (animal) => animal.romaji);