application: takatsugawa-zukan
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Set "Cache-Control" and "Expires" HTTP headers to only cache for two minutes.
# We do this because we frequently push new changes and rely on AppCache for caching,
# and having old versions of files in the browser cache when an AppCache update arrives
# can result on those old versions becoming "frozen" in AppCache.
default_expiration: "2m"

handlers:
- url: /
  static_files: static/home.html
  upload: static/home\.html

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: static

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)

- url: /(.*\.dart)
  mime_type: text/dart
  static_files: static/\1
  upload: static/(.*\.dart)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.appcache)
  static_files: static/\1
  mime_type: text/cache-manifest
  upload: static/(.*\.appcache)
  expiration: "10m"

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
  
