part of fish;

List<Fish> fish_list = [new Fish("piscis abeazus", "アベハゼ科", "アベハゼ属", "abehaze", "アベハゼ",
            4, true, true, true, false, false, false, true, true),
new Fish("piscis maximus", "魚科", "魚属", "aburabote", "アブラボテ",
            3, true, true, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "akaza", "アカザ",
            2, true, true, false, false, true, true, false, false),
new Fish("piscis maximus", "魚科", "魚属", "amago", "アマゴ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ayu", "アユ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ayukake", "アユカケ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "bora", "ボラ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "dojou", "ドジョウ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "donnko", "ドンコ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "gigi", "ギギ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "gogi", "ゴギ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "gokurakuhaze", "ゴクラクハゼ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "himehaze", "ヒメハゼ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "hinahaze", "ヒナハゼ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "hirasuzuki", "ヒラスズキ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "huna", "フナ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ishidojou", "イシドジョウ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ishidonko", "イシドンコ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "itomoroko", "イトモロコ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "kajika", "カジカ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "kamatuka", "カマツカ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "kawaanago", "カワアナゴ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "kawamutu", "カワムツ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "kawayoshinobori", "カワヨシノボリ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "koi", "コイ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "kurodai", "クロダイ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "magoti", "マゴチ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "mahaze", "マハゼ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "medaka", "メダカ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "mimizuhaze", "ミミズハゼ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "mugituku", "ムギツク",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "namazu", "ナマズ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "numatitibu", "ヌマチチブ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "oikawa", "オイカワ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ooyosinobori", "オオヨシノボリ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "oyanirami", "オヤニラミ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ribbinngo", "リッビンゴ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "sakuramasu", "サクラマス",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "shimadojou", "シマドジョウ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "shimaisaki", "シマイサキ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "shirogisu", "シロギス",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "shirouo", "シロウオ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "sumiukigori", "スミウキゴリ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "sunayatume", "スナヤツメ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "suzuki", "スズキ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "tairikubaratanago", "タイリクバラタナゴ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "titibu", "チチブ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "touyoshinobori", "トウヨシノボリ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ugui", "ウグイ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ukigori", "ウキゴリ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "unagi", "ウナギ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "urohaze", "ウロハゼ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "yamame", "ヤマメ",
            3, false, false, false, false, false, false, false, false),
];

Map<String, Fish> fish_map = new Map.fromIterable(fish_list,
    key: (fish) => fish.romaji);