part of fish;

List<Fish> fish_list = [new Fish("mugilogobius abei", "ハゼ科ハゼ亜科", "アベハゼ属", "abehaze", "アベハゼ",
            4, true, true, true, false, false, false, true, false),
new Fish("tanakia limbata", "コイ科タナゴ亜科", "アブラボテ属", "aburabote", "アブラボテ",
            3, true, true, false, false, true, true, false, false),
new Fish("liobogrus reini", "ギギ科", "アカザ属", "akaza", "アカザ",
            4, true, true, false, false, true, true, false, false),
new Fish("salmo(oncorhynchus)masou macrostimus", "サケ科", "サケ属", "amago", "アマゴ",
            2, true, true, false, false, true, true, false, false),
new Fish("plecoglossus altivelis altivelis", "キュウリウオ科", "アユ属", "ayu", "アユ",
            2, false, false, true, false, false, false, true, false),
new Fish("cottus kazika", "カジカ科", "カジカ属", "ayukake", "アユカケ",
            3, false, false, true, false, false, false, true, false),
new Fish("chaenogobius castaneus", "ハゼ科ハゼ亜科", "ウキゴリ属", "biringo", "ビリンゴ",
            4, false, false, true, false, false, false, true, false),
new Fish("mugil cephalus cephalus", "ボラ科", "ボラ属", "bora", "ボラ",
            1, false, false, true, false, false, false, true, false),
new Fish("misgurnus anguillicaudatus", "ドジョウ科", "ドジョウ属", "dojou", "ドジョウ",
            2, false, false, true, false, false, false, true, false),
new Fish("odontobutis obscura obscura", "ハゼ科カワアナゴ亜科", "ドンコ属", "donko", "ドンコ",
            1, false, false, true, false, false, false, true, false),
new Fish("2", "ギギ科", "ギギ属", "gigi", "ギギ",
            2, true, true, false, false, true, true, false, false),
new Fish("carassius gibelio langsdorfi", "コイ科コイ亜科", "フナ属", "ginbuna", "ギンブナ",
            1, false, false, true, false, false, false, true, false),
new Fish("salvelinus leucomaenis f.imbrius", "サケ科サケ亜科", "イワナ属", "gogi", "ゴギ",
            4, true, true, false, false, false, false, false, false),
new Fish("rhinogobius giurinus", "ハゼ科ハゼ亜科", "ヨシノボリ属", "gokurakuhaze", "ゴクラクハゼ",
            2, false, false, true, false, false, false, true, false),
new Fish("favonigobius gymnauchen", "ハゼ科ハゼ亜科", "ヒメハゼ属", "himehaze", "ヒメハゼ",
            2, false, false, true, false, false, false, true, false),
new Fish("redigobius bikolanus", "ハゼ科ハゼ亜科", "ヒナハゼ属", "hinahaze", "ヒナハゼ",
            3, false, false, true, false, false, false, true, false),
new Fish("piscis maximus", "魚科", "魚属", "hirasuzuki", "ヒラスズキ",
            3, false, false, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "huna", "フナ",
            3, false, false, false, false, false, false, false, false),
new Fish("cobitis takatsuensis", "ドジョウ科", "シマドジョウ属", "ishidojou", "イシドジョウ",
            5, true, true, false, false, true, true, false, false),
new Fish("odontobutis hikimiusu", "ハゼ科カワアナゴ亜科", "ドンコ属", "ishidonko", "イシドンコ",
            5, true, true, false, false, false, false, false, false),
new Fish("squalidus gracilis gracilis", "コイ科カマツカ亜科", "スズモロコ属", "itomoroko", "イトモロコ",
            3, false, false, false, false, false, false, false, false),
new Fish("cottus pollux", "カジカ科", "カジカ属", "kajika", "カジカ",
            5, false, false, false, false, false, false, false, false),
new Fish("pseudogobio", "コイ科カマツカ亜科", "カマツカ属", "kamatuka", "カマツカ",
            2, true, true, false, false, true, true, false, false),
new Fish("eleotris oxycephala", "ハゼ科カワアナゴ亜科", "カワアナゴ属", "kawaanago", "カワアナゴ",
            5, false, false, true, false, false, false, true, false),
new Fish("zacco temmincki", "コイ科ハエジャコ亜科", "オイカワ属", "kawamutu", "カワムツ",
            1, true, true, true, false, true, true, true, false),
new Fish("rhinogobius flumineus", "ハゼ科ハゼ亜科", "ヨシノボリ族", "kawayoshinobori", "カワヨシノボリ",
            2, true, true, false, false, true, true, false, false),
new Fish("cyprinus carpio", "コイ科コイ亜科", "コイ属", "koi", "コイ",
            2, false, false, true, false, false, false, true, false),
new Fish("platycephalus indicus", "コチ科", "コチ属", "koti", "コチ",
            2, false, false, true, false, false, false, true, false),
new Fish("acanthopagrus schlegeli", "タイ科", "クロダイ属", "kurodai", "クロダイ",
            2, false, false, true, false, false, false, true, false),
new Fish("takifugu miphobles", "フグ科", "トラフグ属", "kusahugu", "クサフグ",
            3, false, false, true, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "magoti", "マゴチ",
            3, false, false, false, false, false, false, false, false),
new Fish("acanthogobius flavimanus", "ハゼ科ハゼ亜科", "マハゼ属", "mahaze", "マハゼ",
            2, false, false, true, false, false, false, true, false),
new Fish("oryzias latipes", "メダカ科", "メダカ属", "medaka", "メダカ",
            3, false, false, true, false, false, false, true, false),
new Fish("luciogobius guttatus", "ハゼ科ハゼ亜科", "ミミズハゼ属", "mimizuhaze", "ミミズハゼ",
            4, false, false, true, false, false, false, false, false),
new Fish("pungtungia herzi", "コイ科ヒガイ亜科", "ムギツク属", "mugituku", "ムギツク",
            3, false, false, false, false, false, false, false, false),
new Fish("silurus asotus", "ナマズ科", "ナマズ属", "namazu", "ナマズ",
            3, false, false, true, false, false, false, true, false),
new Fish("tridentiger kuroiwae brevispinis", "ハゼ科ハゼ亜科", "チチブ属", "numatitibu", "ヌマチチブ",
            3, false, false, true, false, false, false, true, false),
new Fish("zacco platypus", "コイ科ハエジャコ亜科", "オイカワ族", "oikawa", "オイカワ",
            3, false, false, false, false, false, false, false, false),
new Fish("rhinogobius sp.ld", "ハゼ科ハゼ亜科", "ヨシノボリ属", "ooyoshinobori", "オオヨシノボリ",
            4, true, true, false, false, false, false, false, false),
new Fish("siniperca(bryttosus)kawamebari", "スズキ科", "ケツギョ属", "oyanirami", "オヤニラミ",
            4, true, true, false, false, false, false, false, false),
new Fish("piscis maximus", "魚科", "魚属", "ribbingo", "リッビンゴ",
            3, false, false, false, false, false, false, false, false),
new Fish("salmo(oncorhynchus)masou masou", "サケ科サケ亜科", "サケ属", "sakuramasu", "サクラマス",
            5, false, false, true, false, false, false, false, false),
new Fish("cobitis biwae", "ドジョウ科", "シマドジョウ属", "shimadojou", "シマドジョウ",
            3, true, true, false, false, true, true, false, false),
new Fish("terapon(rhyncopelates)oxyrhynchus", "シマイサキ科", "コトヒキ属", "shimaisaki", "シマイサキ",
            3, false, false, true, false, false, false, true, false),
new Fish("piscis maximus", "魚科", "魚属", "shirogisu", "シロギス",
            3, false, false, false, false, false, false, false, false),
new Fish("leucopsarion petersi", "ハゼ科ハゼ亜科", "シロウオ属", "shirouo", "シロウオ",
            5, false, false, false, false, false, false, true, false),
new Fish("chaenogobius sp.2", "ハゼ科ハゼ亜科", "ウキゴリ属", "sumiukigori", "スミウキゴリ",
            3, false, false, true, false, false, false, true, false),
new Fish("lampetra(lethenteron)reissneri", "ウナギヤツメ科", "ウナギヤツメ属", "sunayatume", "スナヤツメ",
            5, true, true, false, false, false, false, false, false),
new Fish("lateolabrax japonicus", "スズキ科", "スズキ属", "suzuki", "スズキ",
            2, false, false, true, false, false, false, true, false),
new Fish("rhodeus ocellatus ocellatus", "コイ科タナゴ亜科", "バラタナゴ属", "tairikubaratanago", "タイリクバラタナゴ",
            4, false, false, true, false, false, false, false, false),
new Fish("tridentiner obscurus", "ハゼ科ハゼ亜科", "チチブ属", "titibu", "チチブ",
            2, false, false, true, false, false, false, true, false),
new Fish("rhinogobius sp.or", "ハゼ科ハゼ亜科", "ヨシノボリ属", "touyoshinobori", "トウヨシノボリ",
            4, false, false, true, false, false, false, false, false),
new Fish("leuciscus", "コイ科ウグイ亜科", "ウグイ属", "ugui", "ウグイ",
            1, true, true, true, false, true, true, true, false),
new Fish("chaenogobius urotaenia", "ハゼ科ハゼ亜科", "ウキゴリ属", "ukigori", "ウキゴリ",
            3, false, false, true, false, false, false, true, false),
new Fish("anguilla japonica", "ウナギ科", "ウナギ属", "unagi", "ウナギ",
            3, true, true, true, false, true, true, true, false),
new Fish("glossogobius olivaceus", "ハゼ科ハゼ亜科", "ウロハゼ属", "urohaze", "ウロハゼ",
            3, false, false, true, false, false, false, true, false),
new Fish("cottus reinii", "カジカ科", "カジカ属", "utusemikajika", "ウツセミカジカ",
            3, false, false, true, false, false, false, true, false),
new Fish("salmi(oncorhynchus)masou masou", "サケ科サケ亜科", "サケ属", "yamame", "ヤマメ",
            3, true, true, false, false, true, true, false, false),
];

Map<String, Fish> fish_map = new Map.fromIterable(fish_list,
    key: (fish) => fish.romaji);